import {
  fetchAnimalType,
  deleteAnimalType,
  updateAnimalType,
  addAnimalType,
  fetchAnimal,
  deleteAnimal,
  updateAnimal,
  addAnimal,
  authUser,
  fetchDisease,
  deleteDisease,
  updateDisease,
  addDisease,
  fetchPersonnel,
  updatePersonnel,
  addPersonnel,
  fetchPosition,
  deletePosition,
  updatePosition,
  addPosition,
} from "./reducers";

export {
  fetchAnimalType,
  deleteAnimalType,
  updateAnimalType,
  addAnimalType,
  fetchAnimal,
  deleteAnimal,
  updateAnimal,
  addAnimal,
  authUser,
  fetchDisease,
  deleteDisease,
  updateDisease,
  addDisease,
  fetchPersonnel,
  updatePersonnel,
  addPersonnel,
  fetchPosition,
  deletePosition,
  updatePosition,
  addPosition,
};
