export default {
  ANIMAL_TYPE: "animal-type",
  USER: "user",
  PERSONNEL: "personnel",
  ANIMAL: "animal",
  DISEASE: "disease",
  ADD: "add",
  EDIT: "edit",
  AUTH: "auth",
  LOGIN: "login",
  REGISTER: "register",
  DASHBOARD: "dashboard",
  POSITION: "position",
  SETTING: "setting",
  ADOPT: "adopt",
  CONFIRM: "confirm",
  MY_ANIMAL: "my-animal",
  ADOPTION: "adoption",
};
